# Generated by Django 2.2 on 2019-09-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=255, verbose_name='Nome do Evento')),
                ('type', models.CharField(max_length=255, verbose_name='Tipo do Evento')),
                ('start_time', models.DateField(verbose_name='Data de Inicio')),
                ('end_time', models.DateField(verbose_name='Data de termino')),
                ('total_time', models.IntegerField(verbose_name='Carga Horaria')),
                ('description', models.TextField(verbose_name='Descrição do evento')),
                ('state', models.CharField(max_length=255, verbose_name='Estado')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('street', models.CharField(max_length=500, verbose_name='Rua')),
                ('street_number', models.CharField(max_length=8, verbose_name='Número')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('long', models.CharField(max_length=255, verbose_name='Longitude')),
                ('lat', models.CharField(max_length=255, verbose_name='Latitude')),
                ('instagram', models.CharField(max_length=255, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=255, verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Evento',
                'ordering': ['-id'],
            },
        ),
    ]
