# Generated by Django 2.2 on 2019-08-05 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255, verbose_name='Nome do Evento')),
                ('type', models.CharField(max_length=255, verbose_name='Tipo do Evento')),
                ('start_time', models.CharField(max_length=255, verbose_name='Data de Inicio')),
                ('end_time', models.CharField(max_length=255, verbose_name='Data de termino')),
                ('total_time', models.CharField(max_length=255, verbose_name='Carga Horaria')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição do evento')),
                ('state', models.CharField(max_length=255, verbose_name='Estado')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('street', models.CharField(max_length=500, verbose_name='Rua')),
                ('street_number', models.IntegerField(verbose_name='Número')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('long', models.CharField(max_length=255, verbose_name='Longitude')),
                ('lat', models.CharField(max_length=255, verbose_name='Latitude')),
                ('instagram', models.CharField(max_length=255, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=255, verbose_name='Facebook')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=255, verbose_name='Último Nome')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('speciality_institution', models.CharField(max_length=255, verbose_name='Cargo/Instituição')),
                ('biography', models.CharField(max_length=255, verbose_name='Biografia')),
                ('image', models.ImageField(upload_to='')),
                ('lattes', models.CharField(max_length=255, verbose_name='Lattes')),
                ('facebook', models.CharField(max_length=255, verbose_name='Facebook')),
                ('linkedin', models.CharField(max_length=255, verbose_name='Linkedin')),
                ('twitter', models.CharField(max_length=255, verbose_name='Twitter')),
                ('github', models.CharField(max_length=255, verbose_name='Github')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nome da Atividade')),
                ('image', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=255, verbose_name='Tipo da Atividade')),
                ('start_time', models.CharField(max_length=255, verbose_name='Tipo da Atividade')),
                ('total_time', models.CharField(max_length=255, verbose_name='Tipo da Atividade')),
                ('local', models.CharField(max_length=255, verbose_name='Tipo da Atividade')),
                ('description', models.CharField(max_length=255, verbose_name='Tipo da Atividade')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Speaker', verbose_name='Tipo da Atividade')),
            ],
        ),
    ]
