# Generated by Django 2.2 on 2019-08-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Evento'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-id'], 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividade'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['-id'], 'verbose_name': 'Convidado', 'verbose_name_plural': 'Convidados'},
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
