# Generated by Django 2.2 on 2019-08-05 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190804_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='session',
            name='local',
            field=models.CharField(max_length=255, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='session',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Speaker', verbose_name='Convidado'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='total_time',
            field=models.CharField(max_length=255, verbose_name='Carga horaria'),
        ),
    ]
