# Generated by Django 2.2 on 2019-08-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190804_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateField(verbose_name='Data de termino'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateField(verbose_name='Data de Inicio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_time',
            field=models.IntegerField(verbose_name='Carga Horaria'),
        ),
    ]
