# Generated by Django 2.2 on 2019-08-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190825_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='street_number',
            field=models.CharField(max_length=8, verbose_name='Número'),
        ),
    ]
