# Generated by Django 2.2 on 2019-09-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=255, verbose_name='Último Nome')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('speciality_institution', models.CharField(max_length=255, verbose_name='Cargo/Instituição')),
                ('biography', models.CharField(max_length=255, verbose_name='Biografia')),
                ('image', models.ImageField(upload_to='media/')),
                ('lattes', models.CharField(max_length=255, verbose_name='Lattes')),
                ('facebook', models.CharField(max_length=255, verbose_name='Facebook')),
                ('linkedin', models.CharField(max_length=255, verbose_name='Linkedin')),
                ('twitter', models.CharField(max_length=255, verbose_name='Twitter')),
                ('github', models.CharField(max_length=255, verbose_name='Github')),
            ],
            options={
                'verbose_name': 'Convidado',
                'verbose_name_plural': 'Convidados',
                'ordering': ['-id'],
            },
        ),
    ]
